import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import {defineConfig} from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/postcss';

const path=(relative:string)=>fileURLToPath(new URL(relative,import.meta.url));
// One HTML entry per vehicle (generated by scripts/build-registry.mjs) so /<id>/ works on any static host.
const pages=fs.existsSync(path('./web'))?fs.readdirSync(path('./web'),{withFileTypes:true}).filter(e=>e.isDirectory()&&fs.existsSync(path(`./web/${e.name}/index.html`))).map(e=>e.name):[];
// AUTONOMY_BASE=/autonomy/ for GitHub project pages; default '/' for a root domain.
const base=process.env.AUTONOMY_BASE||'/';
export default defineConfig({
  base,
  root:path('./web'),
  publicDir:path('./public'),
  plugins:[react()],
  resolve:{alias:{'@':path('./')}},
  css:{postcss:{plugins:[tailwindcss()]}},
  build:{outDir:path('./dist'),emptyOutDir:true,rollupOptions:{input:{main:path('./web/index.html'),...Object.fromEntries(pages.map(id=>[id,path(`./web/${id}/index.html`)]))}}},
});
