import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
const manifest=JSON.parse(fs.readFileSync('public/models/vf9-manifest.json','utf8'));
const bytes=fs.readFileSync('public/models/'+manifest.file);
const asset=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');
const catalog=manifest.objects;const known=['body','glass','doors','cabin','wheels'];
const ids=new Set();let meshes=0;asset.scene.updateMatrixWorld(true);
asset.scene.traverse(o=>{if(o.userData.component){ids.add(o.userData.component);assert.equal(o.userData.component,o.name);assert(known.includes(o.userData.part),`Unknown part ${o.userData.part}`);assert(typeof o.userData.label==='string'&&o.userData.label.length>0)}if(o.isMesh){meshes++;assert(o.geometry.attributes.position.count>0);}});
assert(catalog.length>0,'Manifest has no pieces');
assert.equal(ids.size,catalog.length,'GLB piece count differs from manifest');
assert(catalog.every(p=>ids.has(p.id)),'Manifest lists ids missing from the GLB');
assert(catalog.every(p=>known.includes(p.part)&&p.faces>0));
const box=new THREE.Box3().setFromObject(asset.scene);const size=box.getSize(new THREE.Vector3());
const L=manifest.lengthMeters;
assert(Math.abs(size.x-L)/L<.03,`Length ${size.x.toFixed(3)} m differs from ${L} m (is the model canonicalised along X?)`);
assert(size.z>1.6&&size.z<2.6,`Unexpected width ${size.z}`);assert(size.y>1.2&&size.y<2.2,`Unexpected height ${size.y}`);
assert(box.min.y>-.05&&box.min.y<.05,`Wheels should rest on y=0, got ${box.min.y}`);
console.log(JSON.stringify({meshPieces:ids.size,drawMeshes:meshes,size:size.toArray().map(v=>+v.toFixed(3)),bytes:bytes.length,placeholder:manifest.placeholder,categories:Object.fromEntries(known.map(id=>[id,catalog.filter(p=>p.part===id).length]))},null,2));
